"""nueva columna logo

Revision ID: 4533fbc9f2e9
Revises: 940f55bd334b
Create Date: 2024-11-26 19:01:01.572117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4533fbc9f2e9'
down_revision: Union[str, None] = '940f55bd334b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'empresa',
        sa.Column('logo', sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('empresa','logo')
    # ### end Alembic commands ###
