"""mensaje de la migracion

Revision ID: 6a084af89115
Revises: b1c5f7d9a7e6
Create Date: 2026-04-08 18:35:24.894497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a084af89115'
down_revision: Union[str, Sequence[str], None] = 'b1c5f7d9a7e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pais',
    sa.Column('id_pais', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('codigo_iso', sa.String(length=10), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_pais')
    )
    op.create_index(op.f('ix_pais_id_pais'), 'pais', ['id_pais'], unique=False)
    op.create_table('municipio',
    sa.Column('id_municipio', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('id_departamento', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_departamento'], ['departamento.id_departamento'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_municipio')
    )
    op.create_index(op.f('ix_municipio_id_municipio'), 'municipio', ['id_municipio'], unique=False)
    op.drop_table('temp_json')
    op.add_column('auditoria', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('categoria', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('ciudad', sa.Column('id_ciudad', sa.Integer(), nullable=False))
    op.add_column('ciudad', sa.Column('id_departamento', sa.Integer(), nullable=True))
    op.add_column('ciudad', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_ciudad_id_ciudad'), 'ciudad', ['id_ciudad'], unique=False)
    op.drop_constraint(op.f('ciudad_departamento_codigo_fkey'), 'ciudad', type_='foreignkey')
    op.create_foreign_key(None, 'ciudad', 'departamento', ['id_departamento'], ['id_departamento'], ondelete='CASCADE')
    op.drop_column('ciudad', 'departamento_codigo')
    op.add_column('departamento', sa.Column('id_departamento', sa.Integer(), nullable=False))
    op.add_column('departamento', sa.Column('id_pais', sa.Integer(), nullable=True))
    op.add_column('departamento', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_departamento_id_departamento'), 'departamento', ['id_departamento'], unique=False)
    op.create_foreign_key(None, 'departamento', 'pais', ['id_pais'], ['id_pais'], ondelete='SET NULL')
    op.drop_column('departamento', 'codigo_dane')
    op.add_column('empresa', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'empresa', 'municipio', ['id_municipio'], ['id_municipio'], ondelete='SET NULL')
    op.add_column('marketplace', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('permiso', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('producto', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('publicidad', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('resultado', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('review', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('rol', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('usuario', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'deleted_at')
    op.drop_column('rol', 'deleted_at')
    op.drop_column('review', 'deleted_at')
    op.drop_column('resultado', 'deleted_at')
    op.drop_column('publicidad', 'deleted_at')
    op.drop_column('producto', 'deleted_at')
    op.drop_column('permiso', 'deleted_at')
    op.drop_column('marketplace', 'deleted_at')
    op.drop_constraint(None, 'empresa', type_='foreignkey')
    op.drop_column('empresa', 'deleted_at')
    op.add_column('departamento', sa.Column('codigo_dane', sa.VARCHAR(length=2), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'departamento', type_='foreignkey')
    op.drop_index(op.f('ix_departamento_id_departamento'), table_name='departamento')
    op.drop_column('departamento', 'deleted_at')
    op.drop_column('departamento', 'id_pais')
    op.drop_column('departamento', 'id_departamento')
    op.add_column('ciudad', sa.Column('departamento_codigo', sa.VARCHAR(length=2), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'ciudad', type_='foreignkey')
    op.create_foreign_key(op.f('ciudad_departamento_codigo_fkey'), 'ciudad', 'departamento', ['departamento_codigo'], ['codigo_dane'])
    op.drop_index(op.f('ix_ciudad_id_ciudad'), table_name='ciudad')
    op.drop_column('ciudad', 'deleted_at')
    op.drop_column('ciudad', 'id_departamento')
    op.drop_column('ciudad', 'id_ciudad')
    op.drop_column('categoria', 'deleted_at')
    op.drop_column('auditoria', 'deleted_at')
    op.create_table('temp_json',
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True)
    )
    op.drop_index(op.f('ix_municipio_id_municipio'), table_name='municipio')
    op.drop_table('municipio')
    op.drop_index(op.f('ix_pais_id_pais'), table_name='pais')
    op.drop_table('pais')
    # ### end Alembic commands ###
