"""se agrego columna role y se modifico columna telefono

Revision ID: 940f55bd334b
Revises: cecb1d3630bb
Create Date: 2024-11-20 00:05:13.351304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '940f55bd334b'
down_revision: Union[str, None] = 'cecb1d3630bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'usuario',
        'telefono',
        existing_type=sa.String(15),
        nullable=True
    )
    op.add_column(
        'usuario',
        sa.Column('rol', sa.String(length=20), server_default='user', nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'rol')
    op.alter_column(
        'usuario',
        'telefono',
        nullable=False
    )
    # ### end Alembic commands ###
