"""add missing tables: pais, ciudad, rol, permiso, role_permiso, auditoria, producto

Revision ID: a9f3d1c4b2e4
Revises: e2f277502df5
Create Date: 2026-03-18 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9f3d1c4b2e4'
down_revision: Union[str, Sequence[str], None] = 'e2f277502df5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pais',
    sa.Column('id_pais', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('codigo_iso', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id_pais')
    )
    op.create_index(op.f('ix_pais_id_pais'), 'pais', ['id_pais'], unique=False)

    op.create_table('ciudad',
    sa.Column('id_ciudad', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('id_departamento', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_departamento'], ['departamento.id_departamento'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_ciudad')
    )
    op.create_index(op.f('ix_ciudad_id_ciudad'), 'ciudad', ['id_ciudad'], unique=False)

    op.create_table('rol',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_rol'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_rol_id_rol'), 'rol', ['id_rol'], unique=False)

    op.create_table('permiso',
    sa.Column('id_permiso', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_permiso'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_permiso_id_permiso'), 'permiso', ['id_permiso'], unique=False)

    op.create_table('role_permiso',
    sa.Column('id_rol', sa.Integer(), nullable=True),
    sa.Column('id_permiso', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_permiso'], ['permiso.id_permiso'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_rol'], ['rol.id_rol'], ondelete='CASCADE')
    )

    op.create_table('auditoria',
    sa.Column('id_auditoria', sa.Integer(), nullable=False),
    sa.Column('tabla', sa.String(length=100), nullable=False),
    sa.Column('operacion', sa.String(length=50), nullable=False),
    sa.Column('id_registro', sa.Integer(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_auditoria')
    )
    op.create_index(op.f('ix_auditoria_id_auditoria'), 'auditoria', ['id_auditoria'], unique=False)

    op.create_table('producto',
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('precio', sa.Float(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('id_empresa', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresa.id_empresa'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_producto')
    )
    op.create_index(op.f('ix_producto_id_producto'), 'producto', ['id_producto'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_producto_id_producto'), table_name='producto')
    op.drop_table('producto')
    op.drop_index(op.f('ix_auditoria_id_auditoria'), table_name='auditoria')
    op.drop_table('auditoria')
    op.drop_table('role_permiso')
    op.drop_index(op.f('ix_permiso_id_permiso'), table_name='permiso')
    op.drop_table('permiso')
    op.drop_index(op.f('ix_rol_id_rol'), table_name='rol')
    op.drop_table('rol')
    op.drop_index(op.f('ix_ciudad_id_ciudad'), table_name='ciudad')
    op.drop_table('ciudad')
    op.drop_index(op.f('ix_pais_id_pais'), table_name='pais')
    op.drop_table('pais')
    # ### end Alembic commands ###
