"""Se elimino columna login

Revision ID: cecb1d3630bb
Revises: 4c4d490efa83
Create Date: 2024-11-19 22:58:42.330642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cecb1d3630bb'
down_revision: Union[str, None] = '4c4d490efa83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'login')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('login', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###
