"""crear tablas principales

Revision ID: e2f277502df5
Revises: bb04f13dcd51
Create Date: 2026-03-17 15:56:32.548954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2f277502df5'
down_revision: Union[str, Sequence[str], None] = 'bb04f13dcd51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_categoria')
    )
    op.create_index(op.f('ix_categoria_id_categoria'), 'categoria', ['id_categoria'], unique=False)
    op.create_table('departamento',
    sa.Column('id_departamento', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_departamento')
    )
    op.create_index(op.f('ix_departamento_id_departamento'), 'departamento', ['id_departamento'], unique=False)
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('correo', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('rol', sa.String(length=20), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('correo')
    )
    op.create_index(op.f('ix_usuario_id_usuario'), 'usuario', ['id_usuario'], unique=False)
    op.create_table('municipio',
    sa.Column('id_municipio', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('id_departamento', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_departamento'], ['departamento.id_departamento'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_municipio')
    )
    op.create_index(op.f('ix_municipio_id_municipio'), 'municipio', ['id_municipio'], unique=False)
    op.create_table('resultado',
    sa.Column('id_resultado', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('criterio', sa.String(length=255), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_resultado')
    )
    op.create_index(op.f('ix_resultado_id_resultado'), 'resultado', ['id_resultado'], unique=False)
    op.create_table('empresa',
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('nit', sa.String(length=50), nullable=False),
    sa.Column('correo', sa.String(length=100), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('id_categoria', sa.Integer(), nullable=True),
    sa.Column('id_municipio', sa.Integer(), nullable=True),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id_categoria'], ['categoria.id_categoria'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_municipio'], ['municipio.id_municipio'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_empresa'),
    sa.UniqueConstraint('nit')
    )
    op.create_index(op.f('ix_empresa_id_empresa'), 'empresa', ['id_empresa'], unique=False)
    op.create_table('marketplace',
    sa.Column('id_marketplace', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('precio', sa.Float(), nullable=True),
    sa.Column('imagen_url', sa.String(length=255), nullable=True),
    sa.Column('fecha_publicacion', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('id_categoria', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_categoria'], ['categoria.id_categoria'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresa.id_empresa'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_marketplace')
    )
    op.create_index(op.f('ix_marketplace_id_marketplace'), 'marketplace', ['id_marketplace'], unique=False)
    op.create_table('publicidad',
    sa.Column('id_publicidad', sa.Integer(), nullable=False),
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('tipo_anuncio', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('duracion', sa.Integer(), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresa.id_empresa'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_publicidad')
    )
    op.create_index(op.f('ix_publicidad_id_publicidad'), 'publicidad', ['id_publicidad'], unique=False)
    op.create_table('review',
    sa.Column('id_review', sa.Integer(), nullable=False),
    sa.Column('id_empresa', sa.Integer(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('calificacion', sa.Float(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresa.id_empresa'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_review')
    )
    op.create_index(op.f('ix_review_id_review'), 'review', ['id_review'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_id_review'), table_name='review')
    op.drop_table('review')
    op.drop_index(op.f('ix_publicidad_id_publicidad'), table_name='publicidad')
    op.drop_table('publicidad')
    op.drop_index(op.f('ix_marketplace_id_marketplace'), table_name='marketplace')
    op.drop_table('marketplace')
    op.drop_index(op.f('ix_empresa_id_empresa'), table_name='empresa')
    op.drop_table('empresa')
    op.drop_index(op.f('ix_resultado_id_resultado'), table_name='resultado')
    op.drop_table('resultado')
    op.drop_index(op.f('ix_municipio_id_municipio'), table_name='municipio')
    op.drop_table('municipio')
    op.drop_index(op.f('ix_usuario_id_usuario'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_departamento_id_departamento'), table_name='departamento')
    op.drop_table('departamento')
    op.drop_index(op.f('ix_categoria_id_categoria'), table_name='categoria')
    op.drop_table('categoria')
    # ### end Alembic commands ###
